### ISSUE TITLE
Please update the lwjgl of 1.18.2

### ISSUE THREAD

**Issue by ipiiia** [MinecraftMachina/ManyMC#62]
I want LWJGL 3.3.1🥹

**Comment by ViRb3** [comment]
Every version of MC after 1.12 is using LWJGL 3.3.1.

**Comment by ipiiia** [comment]
Oh  I was mistaken because I saw this.
```
    "name": "LWJGL 3",
    "releaseTime": "2019-06-24T12:52:52+00:00",
    "type": "release",
    "uid": "org.lwjgl3",
    "version": "3.2.2",
    "volatile": true
}
```

**Comment by ViRb3** [comment]
Yes, the current state of the meta is far from perfect, but if you go inside LWJGL 3.2.2's JSON file, you will see it points to 3.3.1 :)
